### ISSUE TITLE
How to check how many completed HITs ?

### ISSUE THREAD

**Issue by noe** [bricksdont/WMT19RefDA#2]
Is there a way to query the system for the number of HITs completed by a user or by an organization?
The amount of time taken to complete them would also be a useful metric to know.

**Comment by bricksdont** [comment]
No, there is no way for you to see those stats on the website. Please email me and I will give you the latest stats for specific users or teams.

I hope that is an acceptable solution for you and kind regards.

**EDIT**: We might also make the statistics available to you in some form, currently discussing.

**Comment by mjpost** [comment]
There is a "Stats" link in the upper right that will show you your statistics.

**Comment by noe** [comment]
Perfect, thanks a lot!

**Comment by bricksdont** [comment]
Hi @noe, just in case you missed this email, we now have a page with user and team stats:

https://docs.google.com/spreadsheets/d/1ONXOmgEN_4mHJDDjgz_5qzC3e1AE2CG1H-vAbpXjeoc/edit?usp=sharing
