### ISSUE TITLE
Submit button disappered

### ISSUE THREAD

**Issue by ChristineBasta** [bricksdont/WMT19RefDA#3]
Hello,
everything was fine in the morning and then now, I completed a task and I can not find the submit button. I am using firefox, Ubuntu, so this is not supposed to happen.  So, what do you suggest?

![Screenshot from 2019-05-24 17-44-26](https://user-images.githubusercontent.com/28846961/58340586-7e1db080-7e4c-11e9-95dd-c1e88c5e06c9.png)

**Comment by mjpost** [comment]
Hi—I'll look into this.

**Comment by mjpost** [comment]
Hi, this is an error I introduced. You might be able to save this session by opening your Javascript console and typing the following:

```
document.getElementById("task_assignment_iframe").contentDocument.getElementById("mturk_form").submit()
```

If not, don't worry, your annotation time is still credited to you.

The error has since been fixed. I am very sorry for the trouble.

**Comment by jairsan** [comment]
A similar thing happened to us around 45min ago.

Account: ggarces 
Task: 10220/assignment/1644/

**Comment by ChristineBasta** [comment]
I lost the session unfortunately.
Thank you for considering it still.

**Comment by mjpost** [comment]
Thanks. The error occurred when I updated the software to include the user stats. I shouldn't have updated it.

You can post the time you spent here if you like, or just factor it in when you are computing how much time you've spent (since it won't be registered in the system).

Again, I'm sorry for the trouble.

**Comment by ChristineBasta** [comment]
It is okay, don't worry.
I took it an average of 75 minutes.
