### ISSUE TITLE
Accidental double-tap of Next button

### ISSUE THREAD

**Issue by myleott** [bricksdont/WMT19RefDA#5]
Since 0% is selected by default, if one mistakenly clicks the Next button twice then it records a 0% annotation. Is there any way to go back and edit the annotation?

**Comment by bricksdont** [comment]
No, unfortunately, there is currently no way to go back and edit the previous judgement.

It is unlikely that we will add such functionality, as it would require major changes to the UI.

My apologies, and kind regards

**Comment by bricksdont** [comment]
Closing this for now, as we will not add this feature for this year's evaluation. Feel free to reopen.
